<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @author      Svetli Nikolov - http://svetli.name
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Content field - remove label column
 * 
 * @see         Magna_News_Block_Adminhtml_News_Edit_Tab_Content
 * @category    design
 * @package     default_default
 * @author      Svetli Nikolov - http://svetli.name
 */
?>
<?php $_element = $this->getElement() ?>
<?php if (!$_element->getNoDisplay()): ?>
<tr>
    <td colspan="3" class="value"><?php echo trim($_element->getElementHtml()) ?></td>
</tr>
<?php endif; ?>