<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Magna
 * @package     Magna_News
 * @copyright   Copyright (c) 2011 Magna Inc. (http://www.magna-studio.eu)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php if ( $this->getNewsData()->getId() ): ?>
	<div class="news-item">
		<div class="item-title">
			<h1><?php echo $this->getNewsData()->getTitle() ?></h1>
		</div>
		<div class="item-date"><?php echo $this->dateFormat( $this->getNewsData()->getDatePosted() ) ?></div>
		<div class="item-details">
			<?php echo $this->getNewsData()->getContent(); ?>
		</div>
		<p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to News List') ?></a></p>
	</div>
<?php endif; ?>
